[build]
##tags = ["cobalt", "dridex", "emotet", "trickbot"]
tags = ["dridex", "trickbot"]
cobalt = "../pcap/cobalt/build/"
dridex = "../pcap/dridex/build/"
emotet = "../pcap/emotet/build/"
trickbot = "../pcap/trickbot/build/"
out_dir = "../out/parsed_malpcap/"
result_dir = "../out/build_results/"

[apply]
#tags = ["cobalt", "dridex", "emotet", "trickbot"]
tags = ["dridex", "trickbot"]
#dir = "../pcap/dridex/validate/"
dir = "../pcap/trickbot/validate/"
out_dir = "../out/parsed_pcap/"
results_dir = "../out/apply_results/"

########################################
#cobalt = "../pcap/cobalt/validate/"
#dridex = "../pcap/dridex/validate/"
#emotet = "../pcap/emotet/validate/"
#trickbot = "../pcap/trickbot/validate/"
########################################