threshold = 0

[build]
tags = ["cobalt", "dridex", "emotet", "trickbot"]

dirs = ["../pcap/dst/", "../pcap/src_dst/"]

cobalt = "cobalt/build/"
dridex = "dridex/build/"
emotet = "emotet/build/"
trickbot = "trickbot/build/"

out_dir = "../out/parsed_malpcap/"
result_dir = "../out/build_results/"

# length_dst length_src_dst types_dst types_src_dst

[apply]
tags = ["cobalt", "dridex", "emotet", "trickbot"]

dirs = ["../pcap/dst/", "../pcap/src_dst/"]

cobalt = "cobalt/validate/"
dridex = "dridex/validate/"
emotet = "emotet/validate/"
trickbot = "trickbot/validate/"

out_dir = "../out/parsed_pcap/"
results_dir = "../out/apply_results/"
results_file = "../out/apply_results/out"

[validate]
tags = ["cobalt", "dridex", "emotet", "trickbot"]
results_file_dict = "../out/validate_results/validate_out_dict"
results_file_all = "../out/validate_results/validate_out_all"
