[build]
##tags = ["cobalt", "dridex", "emotet", "trickbot"]
tags = ["dridex", "trickbot"]
cobalt = "../pcap/cobalt/build/"
dridex = "../pcap/dridex/build/"
emotet = "../pcap/emotet/build/"
trickbot = "../pcap/trickbot/build/"
out_dir = "../out/parsed_malpcap/"
result_dir = "../out/build_results/"

[apply]
#tags = ["cobalt", "dridex", "emotet", "trickbot"]
tags = ["dridex", "trickbot"]
#cobalt = "../pcap/cobalt/validate/"
dridex = "../pcap/dridex/validate/"
#emotet = "../pcap/emotet/validate/"
trickbot = "../pcap/trickbot/validate/"
out_dir = "../out/parsed_pcap/"
results_dir = "../out/apply_results/"
results_file = "../out/apply_results/out"


[validate]
results_file = "../out/validate_results/validate_out"
