[build]
tags = ["cobalt", "dridex", "emotet", "trickbot"]
cobalt = "../pcap/cobalt/build/"
dridex = "../pcap/dridex/build/"
emotet = "../pcap/emotet/build/"
trickbot = "../pcap/trickbot/build/"
out_dir = "../out/parsed_malpcap/"
result_dir = "../out/build_results/"

[apply]
tags = ["cobalt", "dridex", "emotet", "trickbot"]
cobalt = "../pcap/cobalt/validate/"
dridex = "../pcap/dridex/validate/"
emotet = "../pcap/emotet/validate/"
trickbot = "../pcap/trickbot/validate/"
out_dir = "../out/parsed_pcap/"
results_dir = "../out/apply_results/"
results_file = "../out/apply_results/out"

[validate]
tags = ["cobalt", "dridex", "emotet", "trickbot"]
results_file_dict = "../out/validate_results/validate_out_dict"
results_file_all = "../out/validate_results/validate_out_all"
