
[build]
min_length = 1 #min flow length
max_length = 1400 #max flow length
tags = ["dridex", "emotet", "trickbot", "cobalt"]
cobalt = "cobalt/build/"
dridex = "dridex/build/"
emotet = "emotet/build/"
trickbot = "trickbot/build/"

out_dir = "../out/build/parsed_pcap/"
results_dir = "../out/build/results/"

[apply]
# min_length = 1 #min flow length
# max_length = 1400 #max flow length
tags = ["cobalt", "dridex", "emotet", "trickbot", "none"]
cobalt = "cobalt/validate/"
dridex = "dridex/validate/"
emotet = "emotet/validate/"
trickbot = "trickbot/validate/"
none = "none/"

out_dir = "../out/apply/parsed_pcap/"
results_dir = "../out/apply/results/"

[validate]
threshold = 0
min_length = 1 #min flow length
max_length = 1400 #max flow length
tags = ["cobalt", "dridex", "emotet", "trickbot", "none"]

results_dir = "../out/validate/"
