[build]
##tags = ["cobalt", "dridex", "emotet", "trickbot"]
tags = ["dridex"]
cobalt = "/home/ale/uni/tesi/pcap/cobalt/"
##dridex = "/home/ale/uni/tesi/pcap/dridex/"
dridex = "/home/ale/uni/tesi/pcap/dridex/test/"
emotet = "/home/ale/uni/tesi/pcap/emotet/"
trickbot = "/home/ale/uni/tesi/pcap/trickbot/"
out_dir = "../out/parsed_malpcap/"
result_dir = "../out/build_results/"

[apply]
#tags = ["cobalt", "dridex", "emotet", "trickbot"]
tags = ["dridex"]
#dir = "/home/ale/uni/tesi/pcap/"
dir = "/home/ale/uni/tesi/pcap/dridex/test/"
out_dir = "../out/parsed_pcap/"
results_dir = "../out/apply_results/"